name: HyUltXCommand
version: 0.1.3.2.20
author: Hykilpikonna
main: cc.moecraft.hykilpikonna.ult.command.HyUltXCommand
depend: [HyUltimatePlugin]
softdepend: [Vault]
commands:
  hyc:
    description: The command
    usage: /<command> loop start [-delay:<int>] [-period:<int>] [-time:<int>] [-command:{<String>}]
    aliases: [commands]
  pcmd:
    description: Run command as player
    usage: /<command>
    aliases: [playercommand]
  ccmd:
    description: Run command as console
    usage: /<command>
    aliases: [consolecommand]