name: "HyUltimatePlugin"
version: 0.1.7.12.128
description: "Hykilpikonna's combined plugin"
author: Hykilpikonna
main: cc.moecraft.hykilpikonna.ult.Main
softdepend: [HyEssentials]
commands:
    hyu:
        description: The commandRunner to manage this plugin
        usage: /<commandRunner>
        aliases: [hyultimate, hyult]
    hydebug:
        description: CommandRunner debug.
        usage: /<commandRunner>
        aliases: [hydeb]