name: HyUltXFix
version: 0.1.5.14
author: Hykilpikonna
main: cc.moecraft.hykilpikonna.ult.fix.Fix
depend: [HyUltimatePlugin]
commands:
    asinp:
        description: CommandRunner for ASINP.
        usage: /<commandRunner>
        aliases: [antistuckinnetherportal, hyasinp]