name: HyUltXChat
version: 0.1.5.26
author: Hykilpikonna
main: cc.moecraft.hykilpikonna.ult.chat.Chat
depend: [HyUltimatePlugin, HyEssentials]
commands:
    nick:
        description: Change nickname.
        usage: /<commandRunner>
        aliases: [hynick]
    cls:
        description: Clear chat screen.
        usage: /<commandRunner>
        aliases: [hycls, clearchat]