name: HyUltXEssentials
version: 0.1.5.1.15
author: Hykilpikonna
main: cc.moecraft.hykilpikonna.ult.essentials.HyUltXEssentials
depend: [HyUltimatePlugin]
commands:
  hyentity:
    description: The entity command
    usage: /<command>
    aliases: [entity, mob]