name: HyUltXUtil
version: 0.1.5.10.31
author: Hykilpikonna
main: cc.moecraft.hykilpikonna.ult.util.Util
depend: [HyUltimatePlugin]
softdepend: [Essentials]
commands: 
    itemfix:
        description: Fix items for players.
        usage: /<command>
        aliases: [fix, hyfix]
    gethead:
        description: Gets the head of a player.
        usage: /<command>
        aliases: [head, getskull, skull, hyhead]
    health:
        description: Set / lock player's health.
        usage: /<command>
        aliases: [hyhealth, hp]
    foodlevel:
        description: Set / lock player's food level.
        usage: /<command>
        aliases: [fl, food, hyfood]
    fishmodifier:
        description: Command for custom fish.
        usage: /<command>
        aliases: [hyfish, hyfm, fm, fish]
    getuuid:
        description: Get a player's uuid
        usage: /<command> player
        aliases: [hyuuid, uuid]