name: HyUltXUtil
version: 0.1.5.2.2
author: Hykilpikonna
main: cc.moecraft.hykilpikonna.ult.util.Util
depend: [HyUltimatePlugin]
softdepend: [Essentials]
commands: 
    itemfix:
        description: Fix items for players.
        usage: /<command>
        aliases: [fix, hyfix]
    gethead:
        description: Gets the head of a player.
        usage: /<command>
        aliases: [head, getskull, skull, hyhead]
    health:
        description: Set / lock player's health.
        usage: /<command>
        aliases: [hyhealth, hp]
    foodlevel:
        description: Set / lock player's food level.
        usage: /<command>
        aliases: [fl, food, hyfood]
    pullback:
        description: Set pullback for a player.
        usage: /<command>
        aliases: [hypullback, hypb]
    autorespawn:
        description: Set a player to autorespawn.
        usage: /<command>
        aliases: [hyautores, hyar]
    fishmodifier:
        description: CommandRunner for custom fish.
        usage: /<command>
        aliases: [hyfish, hyfl, customfish, fish]